const pagesConfig = [
  { pageId: "home", label: "Home", path: "/" },
  { pageId: "contact", label: "Contact", path: "/contact" },
  { pageId: "about", label: "About", path: "/about" },
  { pageId: "seo-results", label: "SEO Results", path: "/seo-results" },
  { pageId: "packages", label: "Packages", path: "/packages" },
  { pageId: "career", label: "Career", path: "/career" },
  { pageId: "seo-service", label: "SEO Service", path: "/seo-service" },
  { pageId: "ai-seo", label: "AI SEO", path: "/ai-seo" },
  { pageId: "GEO", label: "GEO", path: "/GEO" },
  { pageId: "AEO", label: "AEO", path: "/AEO" },
  { pageId: "Technical-SEO", label: "Technical SEO", path: "/Technical-SEO" },
  { pageId: "Eco-SEO", label: "Eco SEO", path: "/Eco-SEO" },
  { pageId: "social-media-marketing", label: "Social Media Marketing", path: "/social-media-marketing" },
  { pageId: "influencer-marketing", label: "Influencer Marketing", path: "/influencer-marketing" },
  { pageId: "social-listening", label: "Social Listening", path: "/social-listening" },
  { pageId: "ppc", label: "PPC", path: "/ppc" },
  { pageId: "google-shopping-ads", label: "Google Shopping Ads", path: "/google-shopping-ads" },
  { pageId: "display-ads", label: "Display Ads", path: "/display-ads" },
  { pageId: "amazon-ads", label: "Amazon Ads", path: "/amazon-ads" },
  { pageId: "meta-facebook-ads", label: "Meta / Facebook Ads", path: "/meta-facebook-ads" },
  { pageId: "instagram-ads", label: "Instagram Ads", path: "/instagram-ads" },
  { pageId: "linkedin-ads", label: "LinkedIn Ads", path: "/linkedin-ads" },
  { pageId: "Education", label: "Education", path: "/Education" },
  { pageId: "youtube", label: "YouTube", path: "/youtube" },
  { pageId: "Seoseller", label: "Seoseller", path: "/Seoseller" },
  { pageId: "Healthcare", label: "Healthcare", path: "/Healthcare" },
  { pageId: "B2B", label: "B2B", path: "/B2B" },
  { pageId: "Hospitality", label: "Hospitality", path: "/Hospitality" },
  { pageId: "E-Commerce", label: "E-Commerce", path: "/E-Commerce" },
  { pageId: "Travel", label: "Travel", path: "/Travel" },
  { pageId: "Financial-&-Professional", label: "Financial & Professional", path: "/Financial-&-Professional" },
  { pageId: "website-development", label: "Website Development", path: "/website-development" },
  { pageId: "wordpress-development", label: "WordPress Development", path: "/wordpress-development" },
  { pageId: "shopify-development", label: "Shopify Development", path: "/shopify-development" },
  { pageId: "laravel-development", label: "Laravel Development", path: "/laravel-development" },
  { pageId: "woocommerce-development", label: "WooCommerce Development", path: "/woocommerce-development" },
  { pageId: "Wix-Development", label: "Wix Development", path: "/Wix-Development" },
  { pageId: "Website-Maintenance-Services", label: "Website Maintenance Services", path: "/Website-Maintenance-Services" },
  { pageId: "Reseller", label: "Reseller", path: "/Reseller" },
  { pageId: "full-stack-development", label: "Full Stack Development", path: "/full-stack-development" },
  { pageId: "android-ios-development", label: "Android & iOS Development", path: "/android-ios-development" },
];

export default pagesConfig;